services:
  django:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/django/app
      - external-storage:/media/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=videos

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes:
  external-storage:
    external: true
