[project]
name = "imersao-fullcycle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.2",
    "kombu>=5.4.2",
    "pillow>=11.0.0",
    "psycopg2-binary>=2.9.10",
    "ruff>=0.7.0",
]
